# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "histories", :force => true do |t|
    t.integer  "user_id",                     :null => false
    t.integer  "message_id",                  :null => false
    t.datetime "send_at",                     :null => false
    t.integer  "message_type",                :null => false
    t.datetime "deliver_at"
    t.string   "message",      :limit => 256
  end

  create_table "invites", :force => true do |t|
    t.string   "email",       :limit => 256, :default => "", :null => false
    t.string   "invite_code", :limit => 32,  :default => "", :null => false
    t.datetime "create_at",                                  :null => false
    t.datetime "regist_at"
  end

  create_table "users", :force => true do |t|
    t.string   "twitter_id",   :limit => 256, :default => "", :null => false
    t.string   "twitter_pass", :limit => 256, :default => "", :null => false
    t.string   "email",        :limit => 256, :default => "", :null => false
    t.datetime "regist_at",                                   :null => false
    t.boolean  "delete_flag"
  end

end
